-- Supabase에서 실행
CREATE TABLE public.secretary_messages (
  id bigint generated by default as identity primary key,
  user_id text not null,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz default now()
);

CREATE INDEX ON public.secretary_messages (user_id, created_at);
